apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-client
  labels:
    app: pizza-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-client
  template:
    metadata:
      name: pizza-client
      labels:
        app: pizza-client
    spec:
      containers:
        - name: pizza-client
          image: diegoj4v/pizza-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PUBLIC_URL
              value: http://localhost
            #- name: ASTRO_PORT
            #  value: '80'
            #- name: ASTRO_SITE
            #  value: http://localhost
            - name: JWT_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: jwt_domain
            - name: CUSTOMER_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: customer_domain
            - name: ORDER_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: order_domain

---

apiVersion: v1
kind: Service
metadata:
  name: pizza-client-svc
spec:
  selector:
    app: pizza-client
  ports:
    - port: 80
      targetPort: 80