name: Publish pizza data image

on:
   push:
      paths: [backend/pizza-data/**, .github/workflows/pizza_data_workflow.yaml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   ci:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: backend/pizza-data
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend/pizza-data
            fetch-depth: 0
         - uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: '21'
         - name: Test and publish image
           run: ./mvnw spring-boot:build-image -Ddocker-password=${{ secrets.DOCKER_PASSWORD }}