name: Test and publish pizza jwt image

on:
   push:
      paths: [backend/pizza-jwt/**, .github/workflows/pizza_jwt_workflow.yaml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   test:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: backend/pizza-jwt
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend/pizza-jwt
            fetch-depth: 0
         - uses: pnpm/action-setup@v3
           with:
            version: 9
         - uses: actions/setup-node@v4
           with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: backend/pizza-jwt/pnpm-lock.yaml
         - name: Install dependencies
           run: pnpm install --frozen-lockfile
         - name: Test project
           run: pnpm run test

   buid_image:
      needs: [test]
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: backend/pizza-jwt
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend/pizza-jwt
            fetch-depth: 0
         - uses: pnpm/action-setup@v3
           with:
            version: 9
         - uses: actions/setup-node@v4
           with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: backend/pizza-jwt/pnpm-lock.yaml
         - name: Install dependencies
           run: pnpm install --frozen-lockfile
         - name: Build application
           run: pnpm run tsc           
           env: 
            PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
            PRIVATE_URL: ${{ secrets.PRIVATE_URL }}
         - name: Build image
           run: docker build -t diegoj4v/pizza-jwt .
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
            username: diegoj4v
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Push image to docker hub
           run: docker push diegoj4v/pizza-jwt:$(git rev-parse --short ${{ github.sha }})