name: Publish pizza ingredient image

on:
   push:
      paths: [backend/pizza-ingredient/**, .github/workflows/pizza_ingredient_workflow.yaml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

permissions:
   id-token: write

jobs:
   test__and__build__image:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: backend/pizza-ingredient
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend/pizza-ingredient
            fetch-depth: 0
         - uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: '21'
         - name: Test and publish image
           run: ./mvnw spring-boot:build-image -Ddocker-password=${{ secrets.DOCKERHUB_TOKEN }} -Dgit-hash=$(git rev-parse --short ${{ github.sha }}) \
               -DBUCKET_ACCESSKEYID=${{ secrets.BUCKET_ACCESSKEYID }} \
               -DBUCKET_SECRETACCESSKEY=${{ secrets.BUCKET_SECRETACCESSKEY }} \
               -DBUCKET_BUCKET=${{ secrets.BUCKET_BUCKET }}

   #login__and__update__deployment: 
   #   needs: test__and__build__image
   #   runs-on: ubuntu-22.04
   #   steps:
   #      - name: 'Az CLI login'
   #        uses: azure/login@v1
   #        with:
   #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
   #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
   #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         #- name: 'Update image of kubernetes pizza-ingredient deployment'
         #  run: az aks command invoke --resource-group ${{ secrets.AKS_LOCATION }} --name ${{ secrets.AKS_LOCATION }} --command \
         #   "kubectl rollout restart deployment.apps/pizza-ingredient"